config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit, :update]
  resources :favorites, only: [:create, :destroy]
  resources :pictures do
    member do
      get 'favo', action: 'favo'
    end
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  validates :image,  presence: true
  validates :comment, presence: true, length: { maximum: 255 }
  mount_uploader :image, ImageUploader
  has_many :favorites, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 4 }
  mount_uploader :user_image, ImageUploader
  has_many :favorites, dependent: :destroy
  has_many :favorite_pictures, through: :favorites, source: :picture
  has_many :pictures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required
  
  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんの投稿をお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_path, notice: "#{favorite.picture.user.name}さんの投稿をお気に入り解除しました"
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]
  before_action :ensure_current_user_edit_posted_picture, only: [:edit, :update]
  
  def index
    @pictures = Picture.all
    @users = User.all
    @favorites = Favorite.all.where(user_id: current_user.id)
  end
  
  def new
    if params[:back]
      @picture = Picture.new(post_params)
    else
      @picture = Picture.new
    end
  end
  
  def create
    @picture = current_user.pictures.build(post_params)
    if params[:back]
      render :new
    else
      if @picture.save
        PostMailer.post_mail(@picture,current_user).deliver
        redirect_to pictures_path, notice: "投稿しました！"
      else
        render :new
      end
    end
  end
  
  def show
    @picture = Picture.find(params[:id])
  end
  
  def edit
    @picture = Picture.find(params[:id])
  end
  
  def update
    @picture = Picture.find(params[:id])
     if @picture.update(post_params)
      redirect_to pictures_path, notice: "投稿を編集しました！"
    else
      render :edit
    end
  end
  
  def favo
    # @favorite = current_user.favorites.find(user_id: params[:id])
    @favorites = Favorite.where(user_id: current_user.id)
    @pictures = Picture.all
    @users = User.all
  end
  
  def confirm
    @picture = current_user.pictures.build(post_params)
    render :new if @picture.invalid?
  end
  
  def destroy
    @picture.destroy
    redirect_to pictures_path, notice:"投稿を削除しました！"
  end
  
  private
  
  def set_picture
    @picture = Picture.find(params[:id])
  end

  def post_params
    params.require(:picture).permit(:image, :image_cache, :comment)
  end
  
  def ensure_current_user_edit_posted_picture
    @picture = Picture.find(params[:id])
    if @current_user.id != @picture.user_id
      flash[:notice]="権限がありません"
      redirect_to pictures_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to pictures_path
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :ensure_current_user, only: [:edit, :update]

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to pictures_path, notice: "ユーザ登録しました！"
    else
      render :new
    end
  end
  
  def edit
    @user = User.find(current_user.id)
  end
  
  def update
    @user = User.find(current_user.id)
     if @user.update(user_params)
      redirect_to edit_user_path(current_user.id), notice: "ユーザ情報を編集しました！"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,:user_image, :user_image_cache,
                                 :password_confirmation)
  end
  
  def ensure_current_user
    if @current_user.id != params[:id].to_i
      flash[:notice]="権限がありません"
      redirect_to new_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_pictures_path
    elsif action_name == 'edit'
      picture_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaWork</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <header class="header bg-dark py-5">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
  
      <% if logged_in? %>
        <p><%= current_user.name %></p>
        <%= link_to "Edit User", edit_user_path(current_user.id) %>
        <%= link_to "Logout", session_path(current_user.id), method: :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_path %>
        <%= link_to "Login", new_session_path %>
      <% end %>
    </header>
    <main>
      <div class="localNavigation">
        <p>ローカルナビゲーション</p>
        <ul>
          <% if logged_in? %>
            <% if current_user.user_image.present? %>
              <li>
                <%= image_tag current_user.user_image.url, class: "rounded-circle", width: "50px", height: "50px" %>
                <p>プロフィール画像</p>
              </li>
            <% end %>
            <li>
              <%= link_to '投稿する', new_picture_path %>
            </li>
            <li>
              <%= link_to '投稿画像一覧', pictures_path %>
            </li>
            <li>
              <%= link_to 'お気に入り一覧', favo_picture_path(current_user.id) %>
            </li>
          <% else %>
          <% end %>
        </ul>
      </div>
      <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
          <%= yield %>
        </div>
      </div>
    </main>
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright</p>
      </div>
    </footer>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
        <% @picture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col mb-5">
    <div class="card h-100">
      <%= form.label :image %>
      <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
      <%= form.file_field :image %>
      <%= form.hidden_field :image_cache %>
      <div class="card-body p-4">
        <div class="text-center">
          <%= form.label :comment %>
          <%= form.text_field :comment %>
        </div>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @picture, local: true) do |form| %>
  <%= form.hidden_field :image %>
  <%= form.hidden_field :comment %>

  <div class="col mb-5">
    <div class="card h-100">
      <p class="fw-bolder">写真:<%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %></p>
      <%= form.hidden_field :image_cache, class: "card-img-top" %>
      <div class="card-body p-4">
        <div class="text-center">
          <p class="fw-bolder">コメント:<%= @picture.comment %></p>
          <%= form.submit  "登録する" %>
        </div>
      </div>
    </div>
  </div>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/pictures/edit.html.erb
<h2>投稿を編集する</h2>
<%= render 'form' %>

app/views/pictures/favo.html.erb
<h2>お気に入り投稿一覧</h2>

<p><%= notice %></p>


<% @favorites.each do |favorite| %>
<div class="col mb-5">
  <div class="card h-100">
    <% picture=@pictures.find_by(id: favorite.picture_id) %>
    <%= image_tag picture.image.url, class: "card-img-top" %>
    <div class="card-body p-4">
      <div class="text-center">
        <p class="fw-bolder">User Name : <%= (@users.find_by(id: picture.user_id)).name %></p>
        <p class="fw-bolder">Comment : <%= picture.comment %></p>
      </div>
    </div>
  </div>
</div>
<% end %>


<%= link_to '投稿一覧画面へ戻る', pictures_path %>

app/views/pictures/index.html.erb
<h2>投稿一覧</h2>

<p><%= notice %></p>

<% @pictures.each do |picture| %>
  <div class="col mb-5">
    <div class="card h-100">
      <%= image_tag picture.image.url, class: "card-img-top" %>
      <div class="card-body p-4">
        <div class="text-center">
          <p class="fw-bolder">User Name : <%= (@users.find_by(id: picture.user_id)).name %></p>
          <p class="fw-bolder">Comment : <%= picture.comment %></p>
          
          <% unless picture.user_id == current_user.id %>
            <% @favorite = @favorites.find_by(picture_id: picture.id) %>
            <% if @favorite.present? %>
              <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
            <% else %>
              <%= link_to 'お気に入りする', favorites_path(picture_id: picture.id), method: :post, class: 'btn btn-primary' %>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="card-footer p-4 pt-0 border-top-0 bg-transparent text-center">
        <%= link_to '詳細を確認する', picture_path(picture.id), class: 'btn btn-primary' %></td>
        <% if picture.user_id == current_user.id %>
          <%= link_to "投稿を編集する", edit_picture_path(picture.id), mothod: :get , class: 'btn btn-primary', data: { confirm: '本当に編集していいですか？' } %></td>
          <%= link_to '投稿を削除する', picture_path(picture.id), method: :delete , class: 'btn btn-danger', data: { confirm: '本当に削除していいですか？' } %></td>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<%= link_to '投稿する', new_picture_path %>

app/views/pictures/new.html.erb
<h2>画像を投稿する</h2>

<%= form_with(model: @picture, local: true, url: choose_new_or_edit) do |form| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @picture.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col mb-5">
    <div class="card h-100">
      <%= form.label :image %>
      <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
      <%= form.file_field :image , class: "card-img-top" %>
      <%= form.hidden_field :image_cache %>
      <div class="card-body p-4">
        <div class="text-center">
          <%= form.label :comment %>
          <%= form.text_field :comment %>
        </div>
      </div>
    </div>
  </div>
  <%= form.submit %>
<% end %>

app/views/pictures/show.html.erb
<h2>投稿詳細画面</h2>

<p id="notice"><%= notice %></p>

<div class="col mb-5">
  <div class="card h-100">
    <strong>Image:</strong>
    <%= image_tag @picture.image.url , class: "card-img-top" %>
    <div class="card-body p-4">
      <div class="text-center">
        <p class="fw-bolder">コメント: <%= @picture.comment %></p>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Edit', edit_picture_path(@picture) , data: { confirm: '本当に編集していいですか？' } if @picture.user_id == current_user.id %> |
<%= link_to 'Back', pictures_path %>

app/views/users/edit.html.erb
<h2>ユーザ情報を編集する</h2>

<%= form_with(model: @user, local: true ,url: {controller: 'users', action: 'update'}) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
      
    </div>
  <% end %>

  <div class="content">
    <%= form.label :user_image %>
    <%= image_tag(@user.user_image.url) if @user.user_image && @user.user_image.url %>
    <%= form.file_field :user_image %>
    <%= form.hidden_field :user_image_cache %>
  </div>
  <div class="comment">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
    <%= form.label :password %>
    <%= form.password_field :password %>

    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :user_image %>
  <%= image_tag(@user.user_image.url) if @user.user_image && @user.user_image.url %>
  <%= f.file_field :user_image %>
  <%= f.hidden_field :user_image_cache %>
  
  <%= f.submit "Create my account" %>
<% end %>